import {React, PropTypes, Utils, If, Field, Repository, Record, CRUDE, Endpoint, Type, Column} from '../../../core';
import {
    Component,
    Page,
    FontAwesome,
    Link,
    Table,
    PageTitle,
    FieldComponent,
    FieldController,
    Panel
} from '../../../components';
import Button from "../../../component/Button";
import WebApiRepositoryStorage from "../../../repository/storage/WebApiRepoStorage";
import JsonViewer from "../../../component/JsonViewer";


export default class PRecord extends Page {

    record: ?Record = null;
    repo: Repository;
    isNew: boolean;
    viewer: JsonViewer;


    static propTypes = {
        repo: PropTypes.string,
        rec: PropTypes.string
    };

    constructor() {
        super(...arguments);
        this.repo = Repository.get(this.props.repo, true);

        this.isNew = !this.props.rec || this.props.rec === "~new";

        if (this.isNew)
            this.record = this.repo.createRecord(this);
    }


    render() {

        if (!this.isNew && !this.waitForRepo(this.repo, () => this.forceUpdate()))
            return <span>Inicjalizacja repozytorium. Proszę czekać...</span>;

        this.record = this.record || this.repo.get(this, this.props.rec);

        this.record.onFieldChange.listen(this, e => {
            if (!this.viewer)
                return;
            this.viewer.update(this._displayDTO());
        });

        const preview = !this.record.canUpdate;

        const columns = [];

        columns.push(<span key="#action" style={{textAlign: "center"}}>Akcje</span>);

        columns.addAll(this.repo.columns.map((c: Column) =>
            <span key={c.key} style={{textAlign: "center"}}>
                    <div>{c.key}</div>
                    <div style={{fontWeight: "normal"}}>{c.name}</div>
                    <div style={{fontWeight: "normal", fontStyle: "italic"}}>[{c.type.name}]</div>
                </span>));


        return <Panel>
            <PageTitle>{(this.isNew ? "Nowy rekord" : "Edycja rekordu " + this.record.fullId ) + " repozytorium " + this.repo.name}</PageTitle>

            <div style={{
                display: "flex"
            }}>

                <section
                    ref={tag => {
                        // new MutationObserver(mutations => {
                        //     mutations.forEach((mutation: MutationRecord) => {
                        //         console.log(mutation.type);
                        //     });
                        // }).observe(tag, {attributes: true, childList: true, characterData: true});

                    }}

                    style={{
                        flex: "auto",
                        display: "inline-block",
                        // resize: "horizontal",
                        // overflow: "auto",
                        padding: "8px",
                        border: "1px solid #aaa"
                    }}>

                    <table className="tbl" style={{width: "100%"}}>
                        <tbody>
                        {
                            Utils.forEach(this.record.fields, (field: Field) => {

                                // if (this.isNew)
                                //     field.readOnly = false;

                                if (this.isNew && field.config.autoGenerated) return null;

                                return <tr key={field.key}>
                                    <Title field={field}/>
                                    <td >
                                        <FieldController
                                            field={field}
                                            handleRequired={true}
                                            handleFieldError={true}
                                            handleFieldWarning={true}
                                            handleDescription={true}
                                        />
                                    </td>
                                    <td style={{
                                        padding: "4px"
                                    }}>
                                        <FieldComponent
                                            field={field}
                                            fieldCtrl={false}
                                            preview={preview}
                                        />
                                    </td>
                                    <td >
                                        <FieldController field={field} handleDescription={true}/>
                                    </td>

                                </tr>
                            })
                        }

                        </tbody>
                    </table>

                    <div style={{textAlign: "right"}}>

                        <Button record={this.record}
                                crude={this.isNew ? CRUDE.CREATE : CRUDE.UPDATE}

                        > {this.isNew ? "Utwórz" : "Zapisz"} </Button>
                        {this.isNew ? null :
                            <Button confirm={"Czy na pewno usunąć rekord?"} record={this.record}
                                    crude={CRUDE.DELETE}>Usuń</Button>}
                        <Button>Anuluj</Button>
                    </div>

                </section>

                <div style={{flex: "auto", padding: "8px"}}>
                    <div>DTO:</div>
                    <JsonViewer object={this._displayDTO()} instance={e => this.viewer = e}/>
                </div>

            </div>
        </Panel>
    }


    _displayDTO() {
        let dto = WebApiRepositoryStorage.buildDTO([this.record], true);
        dto = dto[this.record.repo.key];
        if (!dto) return;
        dto = dto[0];
        if (!dto) return;
        return dto;
    }
}

class Title extends Component {

    field: Field;
    updated: boolean = false;

    constructor() {
        super(...arguments);
        this.field = this.props.field;
        this.field.onUpdate.listen(this, () => {
            this.updated = true;
            this.forceUpdate();
        });
    }

    render() {
        return <td style={ {
            textAlign: "right",
            color: this.updated ? "blue" : null,
            fontWeight: this.updated ? "bold" : null,
            // verticalAlign: "top"
        } }>{this.field.name + ":"}</td>
    }


}