import {React, PropTypes, Field, Utils, Column, Repository, Record, Type, If, CRUDE} from '../../../core';
import {Page, Icon, Link, Table, FCtrl, Panel, Button, Attributes, Attr} from '../../../components';

function A(props) {
    if (!If.isDefined(props.value))
        return null;
    return <Attr name={props.name} value={Utils.escape(props.value)}/>
}

export default class PRepoDetails extends Page {


    constructor() {
        super(...arguments);
        this.waitForRepo(this.props.repo);
    }


    render() {

        const repo: Repository = Repository.get(this.props.repo, true);


        return <Panel fit scrollable>
            {super.renderTitle("Szczegóły repozytorium " + Utils.escape(repo.name))}

            {  repo.columns.map((c: Column) =>
                <Attributes>
                    <h3>{c.name}</h3>
                    <Attr ifDefined type={Type.STRING} name="Klucz" value={c.key}/>
                    <Attr ifDefined type={Type.STRING} name="Nazwa" value={c.name}/>
                    <Attr ifDefined type={Type.STRING} name="Podtytuł" value={c.subtitle}/>
                    <Attr ifDefined type={Type.STRING} name="Hint" value={c.hint}/>
                    <Attr ifDefined type={Type.STRING} name="Opis" value={c.description}/>
                    <Attr ifDefined type={Type.STRING} name="Typ" value={c.type.name}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Wymagane" value={c.required}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Ukryta" value={c.hidden}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Tylko do odczytu" value={c.readOnly}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Unikalne" value={c.unique}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Przycięte" value={c.trimmed}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Automatycznie generowane" value={c.autoGenerated}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Na żądanie" value={c.onDemand}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Klucz obcy" value={c.foreign}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Enumerata" value={c.enumerate}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Jednostki" value={c.units}/>
                    <Attr ifDefined type={Type.STRING} name="Domyślna jednostka" value={c.defaultUnit}/>
                    <Attr ifDefined type={Type.INT} name="Minimum" value={c.min}/>
                    <Attr ifDefined type={Type.INT} name="Maksimum" value={c.max}/>
                    <Attr ifDefined type={Type.STRING} name="Wyrażenie regularne" value={c.regex}/>
                    <Attr ifDefined type={Type.STRING} name="Wartość domyślna" value={c.defaultValue}/>
                    <Attr ifDefined type={Type.STRING} name="Konwersja wielkości" value={c.textCasing}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Walidator" value={!!c.validator}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Sortowalne" value={c.sortable}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Filtrowalne" value={c.filterable}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Wyszukiwalne" value={c.searchable}/>
                    <Attr ifDefined type={Type.BOOLEAN} name="Kolejność sortowania" value={c.sortOrder}/>
                </Attributes>)}

        </Panel>

    }
}

