package model.repository;

import com.json.JElement;
import com.model.repository.Column;
import com.model.repository.ForeignColumn;
import com.model.repository.Repository;
import com.utils.date.TDate;
import com.utils.reflections.datatype.DataType;
import static model.repository.RResource.VALUE;

public class RCatalogAttributeValues extends Repository<Integer> {

    public final static Column<Integer> ID = new Column<>(c -> {
        c.repository = RCatalogAttributeValues.class;
        c.type = DataType.INT;
        c.readOnly = true;
        c.unique = true;
        c.autoGenerated = true;
        c.key = "id";
        c.name = "ID";
    });

    public final static ForeignColumn<Integer, RCatalogAttribute> ATTR = new ForeignColumn<>(c -> {
        c.repository = RCatalogAttributeValues.class;
        c.type = DataType.INT;
        c.key = "catAttr";
        c.name = "Katalog";
    }, RCatalogAttribute.ID);

    public final static ForeignColumn<Integer, RAttributeElement> ELM = new ForeignColumn<>(c -> {
        c.repository = RCatalogAttributeValues.class;
        c.type = DataType.INT;
        c.key = "attrElm";
        c.name = "Element";
    }, RAttributeElement.ID);

    public final static Column<JElement> VALUE = new Column<>(c -> {
        c.repository = RCatalogAttributeValues.class;
        c.type = DataType.JSON;
        c.key = "value";
        c.name = "Wartość";
    });

    public RCatalogAttributeValues() {
        super(c -> {
            c.key = "catalogAttrValues";
            c.daoName = "data.catalog_attribute_values";
            c.name = "Wartości atrybutu katalogu";
            c.primaryKey = ID;
            c.displayName = VALUE;
        });
    }

}
